---
- name: Check the OS version
  hosts: localhost
  gather_facts: yes

  tasks:
  - name: Check the IP address
    debug: msg="{{ ansible_default_ipv4 }}"
  - name: Check the relase version
    debug: msg="{{ ansible_distribution }}"
  - name: Check the ansible_architecture
    debug: msg="{{ ansible_architecture }}"
  - name: Interface name
    debug: msg="{{ ansible_eth0.device }}"
...
