---
- name: Check the OS version
  hosts: all
  gather_facts: yes

  tasks:
  - name: Check the IP address
    debug: msg="{{ ansible_default_ipv4.gateway }}"
  - name: Check the relase version
    debug: msg="{{ ansible_distribution_version }}"
    
  tasks:
  - name: Check the http status
    apt:
      service: httpd
      status: present
...
